CRYPTSETUP_VERSION := 1.7.5

truncate_version = $(subst $(eval) $(eval),.,$(wordlist 1,$(1),$(subst ., ,$(2))))

KORG_TARS := https://www.kernel.org/pub/linux/utils/cryptsetup/v$(call truncate_version,2,$(CRYPTSETUP_VERSION))/cryptsetup-$(CRYPTSETUP_VERSION).tar
